//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nclass17
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Parts = new HashSet<Part>();
        }
    
        public int OrderID { get; set; }
        public string OrderInfo { get; set; }
        public string OrderNumber { get; set; }
        public string OrderDate { get; set; }
        public string OrderPrice { get; set; }
        public string OrderHistory { get; set; }
        public int CustomerCustomerID { get; set; }
    
        public virtual ICollection<Part> Parts { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
