//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nclass17
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public Part()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int PartID { get; set; }
        public string PartName { get; set; }
        public string PartNumber { get; set; }
        public string PartDescription { get; set; }
        public string PartPrice { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
